version: "3.9"
services:

  backend:
    privileged: true
    build: ./Backend 
    image: chp_backend:latest
    container_name: CHP_Backend
    env_file: Backend/.env 
    ports:
      - 3000:3000

  postgresql:
    image: postgres:15
    restart: always
    env_file:
      - ./Backend/DB/postgresql.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data: